name: GitHub Pages
on: push

jobs:
  build:
  
    name: Build and update blog
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Commit Update
        run: |
          echo ":: Eliminando versión previa ::"
          rm -rf docs
      - name: Build drafts
        run: hugo -D
      - name: Commit Update
        run: |
          echo ":: Renombrando nueva version ::"
          mv public/ docs/
          git config --global user.email "ruben.orrostieta@gmail.com"
          git config --global user.name "ruben"
          git add .
          git commit -m "GitHub Actions: Build ok"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
